### ISSUE TITLE
Specify which music service account to use

### ISSUE THREAD

**Issue by jaburges** [amelchio/sonos#2]
Hi there,
Not sure if this is correct https://developer.sonos.com/reference/control-api/musicserviceaccounts/musicserviceaccount/

But is it possible to add the ability to specify which (in my case Spotify) account to use when sending `media_player.sonos_device`

I use spotify for playing baby music and white noise - hence my discovery weekly etc is full of nature sounds and baby songs lol.

In sonos I have added an account for my son (family spotify plan) and would like to be able to run a script like this:

```yaml
script:
  cbp_more_please:
      sequence:
        - service: media_player.play_media
          data:
            entity_id: "{{ sonos_entity }}"
            music_service_account: "ACCOUNTNAME"
            media_content_id: 'https://open.spotify.com/album/4IjjmD5S292op49x0kc677'
            media_content_type: music
```
